<?php
/**
 * @file
 * menu_link.517f7f61e5fbbd16210c6ad7866f74f10b34c91e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => '<void1>',
  'link_title' => 'About Us',
  'menu_name' => 'main-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
    'unaltered_hidden' => '0',
    'external' => TRUE,
  ),
  'router_path' => '<void1>',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
