<?php
/**
 * @file
 * menu_link.7daf92badf6b9244fb58da1e77a0cd6391c88aa0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => '<void2>',
  'link_title' => 'Our Team',
  'menu_name' => 'main-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
    'unaltered_hidden' => '0',
    'external' => TRUE,
  ),
  'router_path' => '<void2>',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
