<?php
/**
 * @file
 * menu_link.d28107048ecdb8cb661b0016369861fbc25feff4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => '<void>',
  'link_title' => 'Home',
  'menu_name' => 'main-menu',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
    'unaltered_hidden' => '0',
    'external' => TRUE,
  ),
  'router_path' => '<void>',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
